branches:
  only:
    - master

language: node_js

os:
  - linux

sudo: false

services:
  - docker

node_js:
  - "12"
  - "10"

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

git:
  depth: 1

install:
  - npm install
  - npm install coveralls --save-dev

before_script:
  - npm run build;

script:
  - npm run nyc-ci

after_success:
  - npm run coverage
  - npm pack
  - 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_NODE_VERSION" == "8" ]; then
      docker build -t rcjsuen/docker-langserver . || travis_terminate 1;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || travis_terminate 1;
      docker push rcjsuen/docker-langserver || travis_terminate 1;
    fi'
